import { motion } from 'framer-motion';
import { fadeUp, staggerContainer, fadeLeft, fadeRight } from '../utils/animations';
import SectionHeading from '../components/SectionHeading/SectionHeading';
import GlassCard from '../components/Card/Card';
import Button from '../components/Button/Button';
import { HiOutlineDocumentText, HiOutlinePhotograph, HiOutlineVideoCamera, HiOutlineDocumentSearch, HiOutlineChip, HiOutlineShieldCheck, HiOutlineLightningBolt, HiOutlineGlobe } from 'react-icons/hi';

const detailedFeatures = [
  {
    icon: HiOutlineDocumentText,
    title: 'AI Text Detection',
    description: 'Our advanced NLP models analyze writing patterns, sentence structures, and linguistic markers to determine if text was generated by AI systems like GPT, Claude, or Gemini.',
    capabilities: ['Paragraph-level analysis', 'Multiple AI model detection', 'Confidence scoring', 'Highlighted suspicious sections'],
    color: 'text-primary-cyan',
    bg: 'bg-primary-cyan/10',
    border: 'border-primary-cyan/20',
    glow: 'group-hover:shadow-[0_0_40px_rgba(6,182,212,0.2)]',
  },
  {
    icon: HiOutlinePhotograph,
    title: 'Image Authentication',
    description: 'Deep learning forensic analysis detects AI-generated images by examining pixel-level artifacts, frequency distributions, and metadata inconsistencies.',
    capabilities: ['GAN artifact detection', 'Diffusion model fingerprinting', 'Metadata analysis', 'Noise pattern analysis'],
    color: 'text-primary-purple',
    bg: 'bg-primary-purple/10',
    border: 'border-primary-purple/20',
    glow: 'group-hover:shadow-[0_0_40px_rgba(168,85,247,0.2)]',
  },
  {
    icon: HiOutlineVideoCamera,
    title: 'Video Analysis',
    description: 'Frame-by-frame analysis of video content to identify deepfakes, AI-generated sequences, and manipulated footage with temporal consistency checks.',
    capabilities: ['Frame-by-frame analysis', 'Temporal consistency checks', 'Deepfake detection', 'Audio-visual sync analysis'],
    color: 'text-amber-400',
    bg: 'bg-amber-400/10',
    border: 'border-amber-400/20',
    glow: 'group-hover:shadow-[0_0_40px_rgba(251,191,36,0.2)]',
  },
  {
    icon: HiOutlineDocumentSearch,
    title: 'Document Scanner',
    description: 'Comprehensive document analysis that extracts text and images from PDFs and DOCX files, analyzing each component for AI-generated content.',
    capabilities: ['Multi-format support', 'Embedded image extraction', 'Section-by-section analysis', 'Batch processing'],
    color: 'text-emerald-400',
    bg: 'bg-emerald-400/10',
    border: 'border-emerald-400/20',
    glow: 'group-hover:shadow-[0_0_40px_rgba(52,211,153,0.2)]',
  },
];

const additionalFeatures = [
  { icon: HiOutlineChip, title: 'Multi-Model Ensemble', description: 'Multiple AI models work together for higher accuracy.', color: 'text-primary-cyan', bg: 'bg-primary-cyan/10' },
  { icon: HiOutlineShieldCheck, title: 'Privacy First', description: 'Zero data retention. Files deleted after analysis.', color: 'text-emerald-400', bg: 'bg-emerald-400/10' },
  { icon: HiOutlineLightningBolt, title: 'Real-Time Results', description: 'Get results in under 5 seconds per file.', color: 'text-amber-400', bg: 'bg-amber-400/10' },
  { icon: HiOutlineGlobe, title: 'API Access', description: 'RESTful API for integration into your workflow.', color: 'text-primary-purple', bg: 'bg-primary-purple/10' },
];

export default function FeaturesPage() {
  return (
    <div className="pt-24">
      {/* Hero Section */}
      <section className="section-padding">
        <div className="max-w-7xl mx-auto">
          <motion.div
            variants={staggerContainer}
            initial="hidden"
            animate="visible"
            className="text-center max-w-3xl mx-auto"
          >
            <motion.h1 variants={fadeUp} className="text-4xl md:text-5xl lg:text-6xl font-bold font-heading mb-6">
              Powerful <span className="gradient-text">Features</span>
            </motion.h1>
            <motion.p variants={fadeUp} className="text-gray-400 text-lg md:text-xl leading-relaxed mb-8">
              Explore our comprehensive suite of AI content detection tools, designed for accuracy, speed, and ease of use.
            </motion.p>
            <motion.div variants={fadeUp}>
              <Button variant="primary" size="lg" to="/#upload-demo">
                Try It Now
              </Button>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Detailed Features */}
      <section className="section-padding">
        <div className="max-w-7xl mx-auto space-y-16">
          {detailedFeatures.map((feature, index) => {
            const Icon = feature.icon;
            const isReversed = index % 2 !== 0;
            return (
              <motion.div
                key={feature.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.2 }}
                className={`grid grid-cols-1 lg:grid-cols-2 gap-12 items-center ${isReversed ? 'lg:direction-rtl' : ''}`}
              >
                <motion.div variants={isReversed ? fadeRight : fadeLeft} className={isReversed ? 'lg:order-2' : ''}>
                  <div className={`w-14 h-14 rounded-xl ${feature.bg} ${feature.border} border flex items-center justify-center mb-5`}>
                    <Icon className={`w-7 h-7 ${feature.color}`} />
                  </div>
                  <h2 className="text-2xl md:text-3xl font-bold font-heading mb-4 text-white">
                    {feature.title}
                  </h2>
                  <p className="text-gray-400 leading-relaxed mb-6">
                    {feature.description}
                  </p>
                  <ul className="space-y-3">
                    {feature.capabilities.map((cap) => (
                      <li key={cap} className="flex items-center gap-3 text-gray-300 text-sm">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" className={feature.color}>
                          <path d="M9 12l2 2 4-4" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
                          <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="1.5" opacity="0.3"/>
                        </svg>
                        {cap}
                      </li>
                    ))}
                  </ul>
                </motion.div>

                <motion.div variants={isReversed ? fadeLeft : fadeRight} className={isReversed ? 'lg:order-1' : ''}>
                  <div className={`glass rounded-2xl p-8 relative overflow-hidden transition-all duration-500 ${feature.glow} group`}>
                    <div className={`absolute top-0 right-0 w-40 h-40 bg-gradient-to-bl ${feature.bg} rounded-bl-full opacity-30`} />
                    <div className="relative z-10 flex items-center justify-center h-48">
                      <motion.div
                        animate={{ y: [0, -10, 0] }}
                        transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}
                      >
                        <Icon className={`w-24 h-24 ${feature.color} opacity-50`} />
                      </motion.div>
                    </div>
                  </div>
                </motion.div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Additional Features Grid */}
      <section className="section-padding">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.2 }}
            variants={fadeUp}
          >
            <SectionHeading
              title="And More..."
              subtitle="Additional capabilities that make Gaia Detector a complete solution."
            />
          </motion.div>

          <motion.div
            variants={staggerContainer}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.2 }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
          >
            {additionalFeatures.map((feature) => {
              const Icon = feature.icon;
              return (
                <motion.div key={feature.title} variants={fadeUp}>
                  <GlassCard className="text-center">
                    <div className={`w-12 h-12 rounded-xl ${feature.bg} flex items-center justify-center mx-auto mb-4`}>
                      <Icon className={`w-6 h-6 ${feature.color}`} />
                    </div>
                    <h3 className="text-white font-semibold font-heading mb-2">{feature.title}</h3>
                    <p className="text-gray-400 text-sm">{feature.description}</p>
                  </GlassCard>
                </motion.div>
              );
            })}
          </motion.div>
        </div>
      </section>
    </div>
  );
}
